// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AppEvent struct {
	ID        int64
	Kind      string
	Body      string
	CreatedAt time.Time
}

type Todo struct {
	ID        string
	Body      string
	Done      bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
