// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountTodos(ctx context.Context) (CountTodosRow, error)
	CreateTodo(ctx context.Context, body string) (Todo, error)
	DeleteTodo(ctx context.Context, id string) (Todo, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (AppEvent, error)
	ListEvents(ctx context.Context, limitRows int32) ([]AppEvent, error)
	ListTodos(ctx context.Context) ([]Todo, error)
	ToggleTodo(ctx context.Context, id string) (Todo, error)
}

var _ Querier = (*Queries)(nil)
