// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"
)

const countTodos = `-- name: CountTodos :one
SELECT
  count(*)::bigint AS total,
  count(*) FILTER (WHERE done)::bigint AS done
FROM todos
`

type CountTodosRow struct {
	Total int64 `json:"total"`
	Done  int64 `json:"done"`
}

func (q *Queries) CountTodos(ctx context.Context) (CountTodosRow, error) {
	row := q.db.QueryRow(ctx, countTodos)
	var i CountTodosRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (body)
VALUES (trim($1))
RETURNING id, body, done, created_at, updated_at
`

func (q *Queries) CreateTodo(ctx context.Context, body string) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, body)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :one
DELETE FROM todos
WHERE id = $1
RETURNING id, body, done, created_at, updated_at
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRow(ctx, deleteTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO app_events (kind, body)
VALUES ($1, $2)
RETURNING id, kind, body, created_at
`

type InsertEventParams struct {
	Kind string `json:"kind"`
	Body string `json:"body"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (AppEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent, arg.Kind, arg.Body)
	var i AppEvent
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, kind, body, created_at
FROM app_events
ORDER BY id DESC
LIMIT $1::int
`

func (q *Queries) ListEvents(ctx context.Context, limitRows int32) ([]AppEvent, error) {
	rows, err := q.db.Query(ctx, listEvents, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppEvent{}
	for rows.Next() {
		var i AppEvent
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT id, body, done, created_at, updated_at
FROM todos
ORDER BY created_at DESC
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodo = `-- name: ToggleTodo :one
UPDATE todos
SET done = NOT done
WHERE id = $1
RETURNING id, body, done, created_at, updated_at
`

func (q *Queries) ToggleTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRow(ctx, toggleTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
